language: php

php:
  - 5.6
  - 5.5
  - hhvm

env:
  global:
    - SYMFONY_ENV=test

cache:
  directories:
    - $HOME/.composer

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm

before_script:
  - composer selfupdate
  - composer install --no-interaction --no-scripts

script:
  - ./vendor/bin/phpunit
